// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WalkMVC.Data;

#nullable disable

namespace WalkMVC.Migrations
{
    [DbContext(typeof(WalksDbContext))]
    [Migration("20230731134256_Initial-Migration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WalkMVC.Models.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Links")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Road")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Spots")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Links = "No links",
                            Name = "Lazeshchyna (Yasinna)",
                            Road = "Using train from Lviv or Ivano-Frankivsk is very conveniet and preferable",
                            Spots = "You can get to mountais Kukul, Petros, Drahobrat, it`s waterfall, lake Ivor and waterfall Trufanets, "
                        },
                        new
                        {
                            Id = 2,
                            Links = "No links",
                            Name = "Dzembronya",
                            Road = "Using regular (12:00, 15:00 am) bus from Verhovyna, Verhovyna can be reached from Ivano-Frankivsk using bus",
                            Spots = "Able to reach awesome mountain Pip Ivan, Dzembronya and it`s waterfall and even second biggest mountain -- Brebenescyl"
                        },
                        new
                        {
                            Id = 3,
                            Links = "No links",
                            Name = "Zaroslak",
                            Road = "Using train or bus to Vorohta, then catching taxi or unregular bus to base Zaroslak",
                            Spots = "Visit Hoverla, polonuna Pozhyzhevska, lake Nesamovute, mountains Rebra, Hytun-Tomnatyk, Shputzi"
                        },
                        new
                        {
                            Id = 4,
                            Links = "No links",
                            Name = "Yaremche",
                            Road = "Using bus from IvanoFrankivsk or train from Frankivsk, Lviv, other cities",
                            Spots = "You can visit various waterfalls, old aqueducs, polonynas and small mountain"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
